{% set version = "0.2.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rcpptoml
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/RcppTOML_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/RcppTOML/RcppTOML_{{ version }}.tar.gz
  sha256: 371391f9ca82221e76a424082ea9ebc5ea2c50f14e8408469b09d7dc3e6f63aa

build:
  merge_build_host: true  # [win]
  skip: true              # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-rcpp                       # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp >=0.11.5
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp >=0.11.5

test:
  commands:
    - $R -e "library('RcppTOML')"           # [not win]
    - "\"%R%\" -e \"library('RcppTOML')\""  # [win]

about:
  home: https://dirk.eddelbuettel.com/code/rcpp.toml.html
  dev_url: https://github.com/eddelbuettel/rcpptoml
  license: GPL-2.0-or-later
  summary: The configuration format defined by 'TOML' (which expands to "Tom's Obvious Markup Language") specifies an excellent format (described at <https://toml.io/en/>) suitable for both human editing as well as the common uses of a machine-readable format. This package uses 'Rcpp' to connect the 'cpptoml' parser written
    by Chase Geigle (in C++11) to R.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
