{% set version = "0.1.5" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rcpptoml
  version: {{ version|replace("-", "_") }}

source:
  fn: RcppTOML_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/RcppTOML_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/RcppTOML/RcppTOML_{{ version }}.tar.gz
  sha256: f7e30bc677d3bd14463458f961e38644740fd6e52370da51e213d1096a6e7934

build:
  merge_build_host: True  # [win]
  number: 0
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - posix                # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('cxx') }}        # [unix]
    - {{ compiler('m2w64_cxx') }}  # [win]
  host:
    - r-base
    - r-rcpp >=0.11.5
  run:
    - r-base
    - r-rcpp >=0.11.5

test:
  commands:
    - $R -e "library('RcppTOML')"  # [not win]
    - "\"%R%\" -e \"library('RcppTOML')\""  # [win]

about:
  home: http://dirk.eddelbuettel.com/code/rcpp.toml.html
  license: GPL (>= 2)
  summary: |
    The configuration format defined by ''TOML'' (which expands to "Tom''s Obvious Markup
    Language") specifies an excellent format (described at <https://github.com/toml-lang/toml>)
    suitable for both human editing as well as the common uses of a machine-readable
    format. This package uses ''Rcpp'' to connect the ''cpptoml'' parser written by
    Chase Geigle (in modern C++11) to R.
  license_family: GPL3

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
