# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1
    - CONFIG=osx_r_base3.5.1

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "K4n/tIGhfXABWwQ8kJ36CJRvug7i8ChDb2Lo1DoIZiD84SHxtM/HLvn4NbVWYjr6gbVNcydKxG/KVUqCKtnqQamYcDLWOIuTkYyiGSANs2cTm61rmaYfQljEhY9awNRmnQMMPC7k28AmWyi/TjTmMijd3jV+VqaH+tuS8urGs3ZQaXxehwXqh2w43OWF6rii6cwEL04l2IBj4qmRwK723TQuVbRlh4/hTfJhC0USpKj3jf463Of92annEZ98+pHa8i6d2lbCguunBoT35WWGseKlhTVoZAHzTre4Uvp4WFlDVgC8mFCumgvup1obJmQhA3I7MyzX+2aRx3O1CxMB9/Cu/BYiPCau55uDIFAIONZQ+I43pp3qv5BHi2rM85nY8lqQdcPt25XuRHXzQmuZoPOKAjaOnp/MSyB8NBWtP2cPQEFsnv/ZJ2I+41g8oqAWJi6H/wpAv2rG9DqUGvZnMHag/2B44Ht4LgepJGUr10j7lUyIH41nCtU2GP9xD+6ZqYt9BokFrJ/e4eZuX6IiqqdEuqGIgaWiuGJisYAaVruuc0eyFjHFI9FDR1c3x+VozU/v9B3pl7WcFZ3zkUhJTiLF8HVotVv4FjHEv2mklRqbaQLxNGnxzX6pVO7FneNxhZILj1HC3nr6GAdoAQno2SjzYD+PP1lVyZZ4SJnXA2I="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
