travis:
  secure:
    BINSTAR_TOKEN: HyS5Z5ycD4XY3UhZBbCmY7yDQa5oxlp33Lp3LNjRmvNlzocPmaIxnypGN6cNRx5B3pDxFOn3unpdupiZbTrCvEjU6lA6RhZ+M4NLBaV6whCyxb+pqtDrf5MwLMsgI4fIXCLcZMST9FiuCSUQQ/IOe41xpfAkQuJcJ15NAPkIMqV0RkKyYmfi4Y+/TTJe3if06U3jlq/gdmfULdadDn91GL+yPeK2bdQlk8gTZVEz2FpiYw3ZY7UY0r/91BAY1pc/2Y0PhUVOneLFrSSt0e99n3b9uvdcnBdguxy6xpMp6OfnDnC3cY7JUUdjz8dzIpt6sML9Lnwi3L/8HnQ4YESJv1mHybJ+ocO5hM4nt3LusseXC1epizOIR/9cagzeUhmaeyql/7bdK3Hl/T2BHlDT8VBIxKTlTv7AEWO5DQ8KWlQvQ0NZY9IHDVIC+ZY2DA6+dXxY1l780WWs68o2gs6b+79mFNBS8F2lBC3tNBL0vDpLaChQ34ynQhJxHtcMS3+hEY585/0vnYrBLyb9Fvm5hx/4vYoh7mRn5Wtc04mWyUwyGgbLsu2ntKzNNHu9IvOWyWwjob1W4AqJOzc/EGolKvZ6p4rl6h1p26C1sjZaEjDBWkkdDBWzoMcioGsLy2unfhdEXJgytj3J1B+XIdnWH0auVvwyMTMusKHubPVBHgI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
