travis:
  secure:
    BINSTAR_TOKEN: K4n/tIGhfXABWwQ8kJ36CJRvug7i8ChDb2Lo1DoIZiD84SHxtM/HLvn4NbVWYjr6gbVNcydKxG/KVUqCKtnqQamYcDLWOIuTkYyiGSANs2cTm61rmaYfQljEhY9awNRmnQMMPC7k28AmWyi/TjTmMijd3jV+VqaH+tuS8urGs3ZQaXxehwXqh2w43OWF6rii6cwEL04l2IBj4qmRwK723TQuVbRlh4/hTfJhC0USpKj3jf463Of92annEZ98+pHa8i6d2lbCguunBoT35WWGseKlhTVoZAHzTre4Uvp4WFlDVgC8mFCumgvup1obJmQhA3I7MyzX+2aRx3O1CxMB9/Cu/BYiPCau55uDIFAIONZQ+I43pp3qv5BHi2rM85nY8lqQdcPt25XuRHXzQmuZoPOKAjaOnp/MSyB8NBWtP2cPQEFsnv/ZJ2I+41g8oqAWJi6H/wpAv2rG9DqUGvZnMHag/2B44Ht4LgepJGUr10j7lUyIH41nCtU2GP9xD+6ZqYt9BokFrJ/e4eZuX6IiqqdEuqGIgaWiuGJisYAaVruuc0eyFjHFI9FDR1c3x+VozU/v9B3pl7WcFZ3zkUhJTiLF8HVotVv4FjHEv2mklRqbaQLxNGnxzX6pVO7FneNxhZILj1HC3nr6GAdoAQno2SjzYD+PP1lVyZZ4SJnXA2I=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
