travis:
  secure:
    BINSTAR_TOKEN: N7o6BZOEbvPqVd9vars7syqjipX0sTHvwl8kS8Uii+ZrGZBjqtkkvNP+d0L1zB9cxmk0rLs8IxKdeQ8Ed5iujL18ad7eauw9dTvDbBc/EZ+vwz/0i9uFuYFuuuL+Na+qrPZZ8kn8Stdg2yCMwE4o5Jo5Cr8vq9gXq/kdyp/TV8YXtXsOaqJQ0rymlL02eluSTJ7O/db8jCpy3ah9ooXjXDvr/HBevQ7vgbMRRpy67VsUvlDLLOxieGKlRbH3l6/h8hMQOPMAQxa58SrXUp0oeGV6LQyIolGiJoMYXDurKSPUCNScGpP0/5tyVGeGdReHdl8NjRLYl+tPGJWuu6AEh144PzLT5sdkbSnO5QwmMWyO/AKJ9RJeiJ8JGiOkkrcm9wOPk4MtCiiQbxQzJxvbP/IK8hgaqAsDK0IlUbSdhXoeXzklSY9WkeNGPW7IkktV1BhAV69yPYkuws90UtpMHrVzHHXkaIYtZaaxcr/j52U1JnvHTLAZkGDf8bybf5Fh9YCZiicIAnuJFuPZiRRV+2od5ewoszcZ5j5bg3+FyYwS+eboU80ggk/YXskdh3/CxPdp04iRj4kd8B+ooop7653A/gafEYxK1PQp9m+i4MZET1f+NCMRf1KkfWyJOryhfuhDwU6thG9BmFkUm5gBa5enjrEdIeCav7j7D5uZrdE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
